version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    restart: unless-stopped
    command: >
      sh -c "pnpm install && pnpm run dev"
